apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhelloworld
    spec:
      containers:
      - name: myhelloworld-demo
        image: kmlchauhan/helloworld:1.1
        ports:
        - name: nodejs-port
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31187
    nodePort: 31187
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: myhelloworld
  type: NodePort
